--wisudo: false
os: linux
dist: trusty
sudo: required
compiler: gcc
python:
  - "3.8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
      - g++-6
      - python-pip
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev
      - gdal-bin
      - libgdal-dev
      - liblapack-dev
env:
  global:
    - NO_NET=1
before_install:
  - if [[ ! -d "$HOME/.local/bin" ]]; then
      mkdir "$HOME/.local/bin";
    fi
  - export PATH="$HOME/.local/bin:$PATH"
  - ln -fs /usr/bin/gfortran-6 "$HOME/.local/bin/gfortran" && gfortran --version
  - ls -l /usr/bin/gfortran-6
  - ln -fs /usr/bin/gcc-6 "$HOME/.local/bin/gcc" && gcc --version
  - ls -l /usr/bin/gcc-6
  - ln -fs /usr/bin/g++-6 "$HOME/.local/bin/g++" && g++ --version
  - ls -l /usr/bin/g++-6
  - export CXX="g++"
  - git clone -b develop --depth 1 https://github.com/jwhite-usgs/pestpp
  - cd pestpp/src
  - bindir=$HOME/bin/linux COMPILER=gcc CXX=g++ FC=gfortran STATIC=no make -j 5 install
  - cd ../../
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export PATH="$HOME/bin/linux:$PATH"
  - 
  - conda update --yes conda
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - ls -l
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas nose matplotlib
  - pip install coveralls
  - pip install pyshp
  - pip install nose-timer
  - pip install nbsphinx
script:
  - export PATH="$HOME/build/jtwhite79/mf6_pest_freyberg/bin/linux:$PATH"
  - export PYTHONPATH=$PYTHONPATH:.
  - nosetests -v --with-id --nocapture --with-timer mf6_pest.py

